[config]
# Выбираем пастельный режим
wallpaper_tool = "awww" # или другой твой инструмент
swatch_algorithm = "Kmeans"
contrast = 0.5
precision = 1024
[templates.waybar]
input_path = "~/.config/waybar/templates/waybar.css"
output_path = "~/.cache/matugen/waybar.css"

[templates.alacritty]
input_path = "~/.config/alacritty/templates/colors.toml"
output_path = "~/.config/alacritty/colors.toml"

[templates.kitty]
input_path = "~/.config/kitty/templates/colors.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.rofi]
input_path = "~/.config/rofi/templates/style.rasi"
output_path = "~/.config/rofi/style.rasi"
