# --- Monitors ---

#monitor=eDP-1, 1920x1080@60.00200, 0x0, 1
monitor=HDMI-A-1, 1920x1080@74.97, 0x0, 1#, mirror, eDP-1

# --- Mouse, Keyboard --- 

input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    #kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1
    accel_profile = flat
    sensitivity = 1.0

    touchpad {
        natural_scroll = false
    }
}
