# Ссылка на оригинал: https://github.com/uiriansan/SilentSDDM

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = $config/wallpapers/current_wallpaper.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2 # SilentSDDM часто использует легкое размытие
    blur_size = 7
}

# ЧАСЫ (как в SilentSDDM [LockScreen.Clock])
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 90
    font_family = RedHatDisplay Bold
    position = 0, 150
    halign = center
    valign = center
}

# ДАТА (как в SilentSDDM [LockScreen.Date])
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 20
    font_family = RedHatDisplay
    position = 0, 60
    halign = center
    valign = center
}

# АВАТАР (круглый, как в теме)
image {
    monitor =
    path = ~/.face # ПУТЬ К ТВОЕМУ АВАТАРУ
    size = 120
    border_size = 0
    rounding = -1 # Делает его идеально круглым
    position = 0, -50
    halign = center
    valign = center
}

# ПОЛЕ ВВОДА (Input Area)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -160
    halign = center
    valign = center
}

# ИМЯ ПОЛЬЗОВАТЕЛЯ
label {
    monitor =
    text = $USER
    color = rgba(255, 255, 255, 1.0)
    font_size = 14
    font_family = RedHatDisplay SemiBold
    position = 0, -115
    halign = center
    valign = center
}
# ИНДИКАТОР РАСКЛАДКИ
label {
    monitor =
    text = $LAYOUT
    color = rgba(255, 255, 255, 0.6)
    font_size = 12
    font_family = RedHatDisplay
    position = 0, -210
    halign = center
    valign = center
}
