$config = $HOME/.config/hypr/

source = $config/autostart.conf
source = $config/keybinds.conf
source = $config/equipment.conf
source = $config/animations.conf
#source = $config/window.conf
source = $config/rules.conf
