# --- Apps ---
bind = SUPER, T, exec, kitty
bind = SUPER, R, exec, rofi -show drun
bind = SUPER, E, exec, nautilus
#bind = SHIFT, T, exec, Telegram
bind = SUPER, B, exec, firefox
bind = SUPER SHIFT, C, exec, code
bind = SHIFT, O, exec, spotify
bind = SUPER, O, exec, obsidian
bind = SUPER, A, exec, AmneziaVPN

# --- Power menu ---
bind = SUPER SHIFT, P, exec, wlogout -C ~/.config/wlogout/style.css -l ~/.config/wlogout/layout -b 5

# --- sleep ---
bind = , F8, exec, hyprlock

# --- Workspaces ---
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# --- Move to workspaces ---
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# --- Special workspace ---
bind = SUPER, S, togglespecialworkspace,
bind = SUPER SHIFT, S, movetoworkspace, special

# --- Move wiondows ---
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

# --- Maind actions for windows---
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen
bind = ALT, SPACE, togglefloating

# --- Window switching ---
bind = SUPER, Tab, cyclenext
bind = SUPER SHIFT, Tab, cyclenext, prev

# --- Mouse (drag/resize) ---
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# --- Screenshots ---
bind = ,PRINT, exec, hyprshot -m region --clipboard-only
bind = SHIFT,PRINT, exec, hyprshot -m region -o ~/png/screenshots
