decoration {
    blur {
        enabled = true
        size = 5
        passes = 2
        new_optimizations = true
        xray = false
	noise = 0.05
    }
}

# wlogout
layerrule {
    name = logout_dialog
    match:namespace = logout_dialog
    no_anim = true
    blur = true
}

# rofi 
layerrule {
	name = rofi
	match:namespace = rofi
	no_anim = true
	blur = true
} 
# hyprshot
layerrule {
    name = hyprpicker
    match:namespace = hyprpicker
    no_anim = true
    blur = false
}

layerrule {
    name = selection
    match:namespace = selection
    no_anim = true
    blur = false
}
